# Generated by Django 3.0.5 on 2020-05-19 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.CharField(default='x', max_length=20, verbose_name='Fecha')),
                ('origen', models.CharField(default='x', max_length=20, verbose_name='Origen')),
                ('valor', models.IntegerField(default=0, verbose_name='Valor')),
                ('codigos', models.CharField(default='hola', max_length=20, verbose_name='Codigos')),
                ('observacion', models.CharField(default='x', max_length=30, verbose_name='Observacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
